window.SYNQ_RELEASES=[
{id:"nav",title:"Nav Dilê Min",date:"2026-08-30",cover:"assets/nav-dile-min.webp",spotify:"https://open.spotify.com/album/4qrLPlQWKMrOqRK52nd0cN",apple:"https://music.apple.com/us/album/nav-dil%C3%AA-min-single/6804521538?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/nav-dil-min-3",featured:true},
{id:"layali",title:"Ya Layali",date:"2026-08-14",cover:"assets/ya-layali.webp",spotify:"https://open.spotify.com/album/6EDGPYUEu9rTaneGYA3MfS",apple:"https://music.apple.com/us/album/ya-layali-single/6799662976?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/ya-layali"},
{id:"cest",title:"C’est La Vie",date:"2026-07-24",cover:"assets/cest-la-vie.webp",spotify:"https://open.spotify.com/album/7jtdWeY2DH0aeF4ENKcLS3",apple:"https://music.apple.com/us/album/cest-la-vie-single/6793251720?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/cest-la-vie"},
{id:"fint",title:"Jeg Sagde Det Fint",date:"2026-07-17",cover:"assets/jeg-sagde-det-fint.webp",spotify:"https://open.spotify.com/album/1invWXVwui2rPrVcV1ysHh",apple:"https://music.apple.com/us/album/jeg-sagde-det-fint-single/6789707472?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/jeg-sagde-det-fint"},
{id:"yine",title:"Yine",date:"2026-07-03",cover:"assets/yine.webp",spotify:"https://open.spotify.com/album/3EIAV5yRtvWQ8Oti6YjhNI",apple:"https://music.apple.com/us/album/yine-single/6785310701?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/yine-2"},
{id:"sol",title:"Efter Solnedgang",date:"2026-06-19",cover:"assets/efter-solnedgang.webp",spotify:"https://open.spotify.com/album/1ftMuSHGfNxa2P2WnyWpbX",apple:"https://music.apple.com/us/album/efter-solnedgang-single/6781952013?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/efter-solnedgang"},
{id:"seven",title:"Şevên Dirêj (Lange Nætter)",date:"2026-06-07",cover:"assets/seven-direj.webp",spotify:"https://open.spotify.com/album/1h6AjKbMuBsid7tADx0mSp",apple:"https://music.apple.com/us/album/%C5%9Fev%C3%AAn-d%C4%B1r%C3%AAj-lange-n%C3%A6tter-single/6775276091?uo=4",youtube:"",hyperfollow:"https://distrokid.com/hyperfollow/synqstudios/evn-drj-lange-ntter"}
];
